services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: classtools
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development
  #   depends_on:
  #     - postgres_pgvector
  #   networks:
  #     - app_network

  # postgres_pgvector:
  #   image: pgvector/pgvector:0.7.4-pg16
  #   restart: always

  #   environment:
  #     POSTGRES_DB: classtools
  #     POSTGRES_USER: classtools
  #     POSTGRES_PASSWORD: classtools
  #   ports:
  #     - "5431:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #     - ./databases:/docker-entrypoint-initdb.d
  #   command: ["postgres"]

  # postgres_pgvector:
  #   container_name: postgres_pgvector
  #   image: timescale/timescaledb-ha:pg16
  #   restart: always

  #   environment:
  #     POSTGRES_DB: classtools
  #     POSTGRES_USER: classtools
  #     POSTGRES_PASSWORD: classtools
  #   ports:
  #     - "5431:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #     - ./databases:/docker-entrypoint-initdb.d
  
  # postgres_pgai:
  #   container_name: postgres_pgai
  #   image: timescale/timescaledb-ha:pg17
  #   restart: always

  #   environment:
  #     POSTGRES_DB: classtools
  #     POSTGRES_USER: classtools
  #     POSTGRES_PASSWORD: classtools
  #   ports:
  #     - "5431:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #     - ./databases-pgai:/docker-entrypoint-initdb.d

  # pgai-vectorizer_worker:
  #   container_name: pgai-vectorizer_worker
  #   image: timescale/pgai-vectorizer-worker:v0.2.1
  #   environment:
  #     PGAI_VECTORIZER_WORKER_DB_URL: postgres://classtools:classtools@postgres_pgai:5432/postgres
  #     OLLAMA_HOST: http://host.docker.internal:11434
  #   command: [ "--poll-interval", "5s" ]

  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   volumes:
  #     - ~/.ollama:/root/.ollama
  #   ports:
  #     - "11434:11434"
  #   networks:
  #     - app_network

volumes:
  db_data: