
### Get futurpedia items

PUT http://localhost:3001/backoffice/tag
Content-Type: application/json

{
    "id": "a26b32ac-0d79-4c6e-a6e7-ea54ba2023cc",
    "imageUrl": "https://i.ibb.co/W0GxSZT/Icon7.png"
}

### Get all tags
GET http://localhost:3001/backoffice/tag