
### Get futurpedia items

POST http://localhost:3000/backoffice/futurpedia/test/update
Content-Type: application/json

{
    "link": "https://www.futurepedia.io/tool/hubspot"
}

### Update futurpedia items
POST http://localhost:3000/backoffice/futurpedia/update
Content-Type: application/json

{
    "route": "https://www.futurepedia.io/ai-tools/spreadsheet-assistant"
}


###  get json
GET http://localhost:3000/futurpedia/json

###  get tags
GET http://localhost:3000/futurpedia/tags