
### Get futurpedia items

GET http://localhost:3000/backoffice/tool?page=1&pageSize=10


### Update futurpedia items
POST http://localhost:3000/backoffice/futurpedia/update
Content-Type: application/json

{
    "route": "https://www.futurepedia.io/ai-tools/marketing"
}

### Generate json
GET http://localhost:3000/backoffice/tool/generate

### Gemini
GET http://localhost:3000/backoffice/tool/gemini?text='podrias resumirme como funciona la IA Claude 3 ?'