
### Get futurpedia items

POST http://localhost:3000/futurpedia/webTools
Content-Type: application/json

{
    "route": "ai-tools/social-media"
}


###  get json
GET http://localhost:3001/tool?page=10&pageSize=12

###  get SUGGESTIONS
GET http://localhost:3000/tool/suggestions?userId=5cc02058-3e2b-4682-a6d2-9823798f8733

###  get SUGGESTIONS PROMPT
GET http://localhost:3000/tool/suggestions/prompt?prompt='soy profesor de ingles, quiero mejorar mis clases'

### search tools
GET http://localhost:3000/tool/search/?page=2&pageSize=2&filters[prompt]='programador'

### get detail
GET http://localhost:3000/tool/detail?id=21a63400-4dff-4d48-bb7c-ddf266abae20
###  get tags
GET http://localhost:3000